name: 'Run App <Your Last Name>, <Your First Name>'

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest  # Ensure this is correct
    steps:
      - uses: actions/checkout@v2
      
      - name: Install .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'
          
      - name: Restore Dependencies
        run: dotnet restore
      
      - name: Build Project
        run: dotnet build --no-restore
      
      - name: Run Unit Tests
        run: dotnet test --no-build --verbosity normal
